version: '3.3'
services:
  db:
    image: 'postgres:16'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ipc
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5436:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
